const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const select={value:'original',children:[],replaceChildren(...nodes){this.children=nodes;}};
const context={document:{querySelector:()=>select,createElement:()=>({})}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('app/web/media-profiles.js','utf8'),context);
context.updateMediaProfiles({state:'queued',variants:[]});
assert.equal(select.children.length,1);
context.updateMediaProfiles({state:'completed',variants:[{profile:'480',width:320,height:180},{profile:'720',width:320,height:180}]});
assert.equal(select.children.length,4);
assert.equal(select.children[2].textContent,'HLS 320×180（480 档上限）');
assert.equal(select.children[3].value,'720');
select.value='720';context.updateMediaProfiles({state:'completed',variants:[{profile:'720',width:360,height:640}]});
assert.equal(select.value,'720');
context.updateMediaProfiles({state:'running'});
assert.equal(select.value,'original');assert.equal(select.children.length,1);
context.updateMediaProfiles({state:'completed'});
assert.match(select.children[2].textContent,/旧任务，尺寸未记录/);
context.updateMediaProfiles({state:'completed',variants:[{profile:'../bad',width:2,height:2},{profile:'480',width:'320',height:180}]});
assert.equal(select.children.length,2);
context.document.querySelector=()=>null;
assert.doesNotThrow(()=>context.updateMediaProfiles({state:'completed'}));
console.log('Media profile UI: 10 assertions passed');
