let currentCategory='',favorites=false,currentVideo=null,danmaku=[],seen=new Set(),lane=0;
async function feed(){const query=new URLSearchParams({q:$('#search').value,category:currentCategory,favorites});const videos=await api('/videos?'+query);$('#feed-count').textContent=`当前显示 ${videos.length} 个作品`;
 $('#feed-title').textContent=favorites?'我的收藏':'最新投稿';$('#feed').innerHTML=videos.length?videos.map(v=>`<button class="video-card" data-id="${v.id}"><div class="thumbnail"><video muted preload="metadata" src="/api/videos/${v.id}/media#t=0.1"></video><span class="play">▶</span></div><h3>${esc(v.title)}</h3><div class="row small muted"><span>${esc(v.category)}</span><span class="spacer"></span><span>${bytes(v.size)}</span></div></button>`).join(''):empty(favorites?'收藏喜欢的作品':'你的社区，从第一份创作开始',favorites?'播放页点收藏后，会出现在这里':'点击右上角投稿，上传一个视频。');$$('.video-card').forEach(b=>b.onclick=guard(()=>watch(b.dataset.id)));}
function states(){$('#like').textContent=currentVideo.liked?'♥ 已点赞':'♡ 点赞';$('#favorite').textContent=currentVideo.favorite?'★ 已收藏':'☆ 收藏';}
async function comments(){const data=await api('/videos/'+currentVideo.id+'/comments');$('#comments').innerHTML=data.length?data.map(c=>`<article style="border-bottom:1px solid var(--line);padding:20px 0"><div class="row small muted"><strong>本地读者</strong><span>${esc(new Date(c.created*1000).toLocaleString())}</span></div><p class="answer">${esc(c.text)}</p></article>`).join(''):empty('来聊聊这部作品','写下第一条评论。');}
async function watch(id){currentVideo=await api('/videos/'+id);$('#browse').classList.add('hidden');$('#watch').classList.remove('hidden');$('#watch-title').textContent=currentVideo.title;$('#description').textContent=currentVideo.description||'创作者暂未添加简介。';$('#video-category').textContent=currentVideo.category;$('#media-info').textContent=`${bytes(currentVideo.size)} · ${new Date(currentVideo.created*1000).toLocaleDateString()}`;$('#player').src='/api/videos/'+id+'/media';states();seen=new Set();$('#danmaku-layer').innerHTML='';danmaku=await api('/videos/'+id+'/danmaku');await comments();window.scrollTo(0,0);}
$('#back').onclick=guard(async()=>{$('#player').pause();$('#player').removeAttribute('src');$('#player').load();$('#watch').classList.add('hidden');$('#browse').classList.remove('hidden');await feed();});
$('#search-form').onsubmit=guard(async e=>{e.preventDefault();await feed();});
$('#favorites').onclick=guard(async()=>{favorites=!favorites;$('#favorites').textContent=favorites?'★ 已筛选收藏':'☆ 我的收藏';await feed();});
$('#upload-open').onclick=()=>$('#upload-dialog').showModal();$('#upload-close').onclick=()=>$('#upload-dialog').close();
$('#upload-form').onsubmit=guard(async e=>{e.preventDefault();const file=$('#video-file').files[0];if(!file)return;if(file.size>512*1024*1024)throw Error('视频超过512MiB');const body=new FormData();body.append('file',file);body.append('title',$('#title').value);body.append('category',$('#category').value);body.append('description',$('#description-input').value);$('#upload-submit').disabled=true;$('#upload-close').disabled=true;$('#upload-progress').classList.remove('hidden');try{await new Promise((resolve,reject)=>{const req=new XMLHttpRequest();req.open('POST','/api/videos');req.upload.onprogress=e=>{if(e.lengthComputable){$('#upload-progress').value=e.loaded/e.total*100;$('#upload-status').textContent=`上传 ${Math.round(e.loaded/e.total*100)}%`;}};req.onload=()=>{let result;try{result=JSON.parse(req.responseText);}catch{result={};}if(req.status>=200&&req.status<300)resolve(result);else reject(Error(result.detail||'上传失败'));};req.onerror=()=>reject(Error('网络连接失败'));req.send(body);});$('#upload-dialog').close();$('#upload-form').reset();toast('作品已发布');await feed();}finally{$('#upload-submit').disabled=false;$('#upload-close').disabled=false;$('#upload-progress').classList.add('hidden');}});
$('#like').onclick=guard(async()=>{currentVideo=await post('/videos/'+currentVideo.id+'/interaction/like',{});states();});$('#favorite').onclick=guard(async()=>{currentVideo=await post('/videos/'+currentVideo.id+'/interaction/favorite',{});states();});
$('#comment-form').onsubmit=guard(async e=>{e.preventDefault();await post('/videos/'+currentVideo.id+'/comments',{text:$('#comment-text').value});$('#comment-text').value='';await comments();});
$('#danmaku-form').onsubmit=guard(async e=>{e.preventDefault();const item=await post('/videos/'+currentVideo.id+'/danmaku',{text:$('#danmaku-text').value,at:$('#player').currentTime});danmaku.push(item);$('#danmaku-text').value='';toast('弹幕已发送');});
$('#player').onerror=()=>toast('无法播放该编码，请使用浏览器支持的MP4/WebM',true);$('#player').onseeking=()=>{seen=new Set();$('#danmaku-layer').innerHTML='';};$('#show-danmaku').onchange=()=>$('#danmaku-layer').classList.toggle('hidden',!$('#show-danmaku').checked);
$('#player').ontimeupdate=()=>{for(const d of danmaku){const delta=$('#player').currentTime-d.at;if(delta>=0&&delta<.8&&!seen.has(d.id)){seen.add(d.id);const node=document.createElement('span');node.className='danmaku';node.textContent=d.text;node.style.top=(8+(lane++%6)*11)+'%';node.onanimationend=()=>node.remove();$('#danmaku-layer').append(node);}}};
guard(async()=>{const config=await api('/config');$('#category').innerHTML=config.categories.map(c=>`<option>${esc(c)}</option>`).join('');$('#categories').innerHTML=['全部',...config.categories].map((c,i)=>`<button class="category-btn ${i?'':'active'}" data-category="${i?esc(c):''}">${esc(c)}</button>`).join('');$$('.category-btn').forEach(b=>b.onclick=guard(async()=>{currentCategory=b.dataset.category;$$('.category-btn').forEach(x=>x.classList.toggle('active',x===b));await feed();}));await feed();})();
