const communityControls=document.createElement('div');communityControls.className='row';communityControls.style.margin='15px 0';communityControls.innerHTML='<button class="btn secondary" id="history-open">观看历史</button><button class="btn secondary" id="collections-open">我的合集</button><button class="btn secondary" id="notices-open">消息</button><button class="btn secondary" id="reports-open">作品举报</button>';
$('#browse').prepend(communityControls);
const communityDialog=document.createElement('dialog');communityDialog.innerHTML='<h2 id="community-title"></h2><div id="community-content"></div><button class="btn secondary" id="community-close">关闭</button>';document.body.append(communityDialog);$('#community-close').onclick=()=>communityDialog.close();
function communityShow(title,html){$('#community-title').textContent=title;$('#community-content').innerHTML=html;communityDialog.showModal();}
$('#history-open').onclick=guard(async()=>{const data=await api('/community/history');communityShow('观看历史',data.map(v=>`<button class="nav-item history-video" data-id="${v.video_id}">${esc(v.title)} · ${Math.round(v.position)} 秒</button>`).join('')||empty('还没有历史','打开一个视频后会自动保存'));$$('.history-video').forEach(b=>b.onclick=guard(async()=>{communityDialog.close();await watch(b.dataset.id);}));});
$('#notices-open').onclick=guard(async()=>{const data=await api('/community/notifications');communityShow('消息',data.map(n=>`<p>${esc(n.text)}<span class="small muted"> · ${new Date(n.created*1000).toLocaleString()}</span></p>`).join('')||empty('暂无消息','作品收到评论后会通知你'));});
$('#reports-open').onclick=guard(async()=>{const data=await api('/community/reports');communityShow('我的作品收到的举报',data.map(r=>`<article><strong>${esc(r.title)}</strong><p>${esc(r.reason)} · ${esc(r.state)}</p><button class="btn secondary resolve-report" data-id="${r.id}">标记已审阅</button></article>`).join('')||empty('没有举报',''));$$('.resolve-report').forEach(b=>b.onclick=guard(async()=>{await post('/community/reports/'+b.dataset.id+'/resolve',{});toast('已标记审阅');communityDialog.close();}));});
$('#collections-open').onclick=guard(async()=>{const data=await api('/community/collections');communityShow('我的合集',`<form id="collection-form" class="row"><input id="collection-name" placeholder="合集名称" required maxlength="60"><button class="btn">创建</button></form>`+data.map(c=>`<article><h3>${esc(c.name)}</h3>${c.videos.map(v=>`<button class="nav-item collection-video" data-id="${v.id}">${esc(v.title)}</button>`).join('')}</article>`).join(''));$('#collection-form').onsubmit=guard(async e=>{e.preventDefault();await post('/community/collections',{name:$('#collection-name').value});communityDialog.close();toast('合集已创建');});$$('.collection-video').forEach(b=>b.onclick=guard(async()=>{communityDialog.close();await watch(b.dataset.id);}));});
const watchActions=document.createElement('div');watchActions.className='row';watchActions.style.margin='15px 0';watchActions.innerHTML='<button class="btn secondary" id="author-open">作者主页</button><button class="btn secondary" id="add-collection">加入合集</button><button class="btn secondary" id="report-video">举报</button><button class="btn secondary" id="edit-video">编辑作品</button><button class="btn secondary" id="remove-video">隐藏作品</button><button class="btn secondary" id="retry-media">重新转码</button><a class="btn secondary hidden" id="hls-link">HLS 播放清单</a><span class="small muted" id="media-state"></span>';
$('#description').after(watchActions);const recommendationBox=document.createElement('div');recommendationBox.id='recommendations';$('.creator').append(recommendationBox);
const baseWatch=watch;watch=async id=>{await baseWatch(id);await post('/community/videos/'+id+'/history?position=0',{});const mine=currentVideo.owner===account.id;['edit-video','remove-video','retry-media'].forEach(x=>$('#'+x).classList.toggle('hidden',!mine));const recommendations=await api('/community/recommendations/'+id);$('#recommendations').innerHTML='<h3>继续发现</h3>'+recommendations.map(v=>`<button class="nav-item recommended" data-id="${v.id}">${esc(v.title)}<br><span class="small">${esc(v.reason)}</span></button>`).join('');$$('.recommended').forEach(b=>b.onclick=guard(()=>watch(b.dataset.id)));const check=async()=>{if(currentVideo?.id!==id)return;const job=await api('/videos/'+id+'/processing');$('#media-state').textContent='媒体处理：'+job.state+(job.error?' · '+job.error:'');if(job.state==='completed'){$('#hls-link').href='/api/videos/'+id+'/assets/master.m3u8';$('#hls-link').classList.remove('hidden');$('#player').poster='/api/videos/'+id+'/assets/poster.jpg';}else{$('#hls-link').classList.add('hidden');if(['running','queued'].includes(job.state))setTimeout(()=>guard(check)(),2000);}};await check();};
$('#author-open').onclick=guard(async()=>{const data=await api('/community/authors/'+currentVideo.owner);communityShow(data.author.username,`<button class="btn" id="follow-author">${data.following?'取消关注':'关注'}</button>`+data.videos.map(v=>`<p>${esc(v.title)}</p>`).join(''));$('#follow-author').onclick=guard(async()=>{const result=await post('/community/authors/'+currentVideo.owner+'/follow',{});$('#follow-author').textContent=result.following?'取消关注':'关注';});});
$('#add-collection').onclick=guard(async()=>{const data=await api('/community/collections');communityShow('选择合集',data.map(c=>`<button class="nav-item choose-collection" data-id="${c.id}">${esc(c.name)}</button>`).join('')||empty('请先创建合集','返回首页点击“我的合集”'));$$('.choose-collection').forEach(b=>b.onclick=guard(async()=>{await post('/community/collections/'+b.dataset.id+'/'+currentVideo.id,{});communityDialog.close();toast('已加入合集');}));});
$('#report-video').onclick=guard(async()=>{const reason=prompt('填写举报原因');if(reason){await post('/community/videos/'+currentVideo.id+'/report',{text:reason});toast('举报已记录');}});
$('#edit-video').onclick=guard(async()=>{const title=prompt('修改标题',currentVideo.title);if(title){await api('/community/videos/'+currentVideo.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description:currentVideo.description})});await watch(currentVideo.id);}});
$('#remove-video').onclick=guard(async()=>{if(!confirm('隐藏自己的作品？数据会保留，可恢复。'))return;await api('/community/videos/'+currentVideo.id,{method:'DELETE'});await $('#back').onclick();toast('作品已隐藏');});$('#retry-media').onclick=guard(async()=>{await post('/community/videos/'+currentVideo.id+'/retry',{});await watch(currentVideo.id);});
let lastHistory=0;$('#player').addEventListener('timeupdate',()=>{if(currentVideo&&Date.now()-lastHistory>10000){lastHistory=Date.now();guard(()=>post('/community/videos/'+currentVideo.id+'/history?position='+$('#player').currentTime,{}))();}});
const uploadCancel=document.createElement('button');uploadCancel.type='button';uploadCancel.className='btn secondary';uploadCancel.textContent='中止上传';$('#upload-progress').after(uploadCancel);uploadCancel.onclick=()=>{if(window.activeUpload)window.activeUpload.abort();};

let hlsInstance=null;const playerMode=document.createElement('select');playerMode.setAttribute('aria-label','播放模式');playerMode.innerHTML='<option value="original">原视频</option><option value="auto">HLS 自动码率</option><option value="480">HLS 480p</option><option value="720">HLS 720p</option>';watchActions.append(playerMode);playerMode.onchange=()=>{if(hlsInstance){hlsInstance.destroy();hlsInstance=null;}const video=$('#player');if(playerMode.value==='original'){video.src='/api/videos/'+currentVideo.id+'/media';return;}const url='/api/videos/'+currentVideo.id+'/assets/'+(playerMode.value==='auto'?'master.m3u8':playerMode.value+'/index.m3u8');if(window.Hls&&Hls.isSupported()){hlsInstance=new Hls({enableWorker:false});hlsInstance.loadSource(url);hlsInstance.attachMedia(video);hlsInstance.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal)toast('HLS未就绪或播放失败，请切回原视频',true);});}else if(video.canPlayType('application/vnd.apple.mpegurl'))video.src=url;else toast('此浏览器不支持HLS',true);};
const watchWithHls=watch;watch=async id=>{if(hlsInstance){hlsInstance.destroy();hlsInstance=null;}playerMode.value='original';await watchWithHls(id);};


const hiddenButton=document.createElement('button');hiddenButton.className='btn secondary';hiddenButton.textContent='隐藏的作品';communityControls.append(hiddenButton);hiddenButton.onclick=guard(async()=>{const data=await api('/community/hidden');communityShow('隐藏的作品',data.map(v=>`<p>${esc(v.title)} <button class="btn secondary unhide-video" data-id="${v.id}">恢复</button></p>`).join('')||empty('没有隐藏作品',''));$$('.unhide-video').forEach(b=>b.onclick=guard(async()=>{await post('/community/videos/'+b.dataset.id+'/restore',{});communityDialog.close();await feed();toast('作品已恢复');}));});
let commentOffset=0;const commentMore=document.createElement('button');commentMore.className='btn secondary';commentMore.textContent='加载更多评论';$('#comments').after(commentMore);const baseComments=comments;comments=async()=>{commentOffset=0;await baseComments();commentMore.classList.toggle('hidden',$('#comments').querySelectorAll('article').length<50);};commentMore.onclick=guard(async()=>{commentOffset+=50;const data=await api('/videos/'+currentVideo.id+'/comments?offset='+commentOffset);$('#comments').insertAdjacentHTML('beforeend',data.map(c=>`<article style="padding:20px 0"><span class="small muted">${esc(new Date(c.created*1000).toLocaleString())}</span><p class="answer">${esc(c.text)}</p></article>`).join(''));commentMore.classList.toggle('hidden',data.length<50);});

